exams/urls.py
from django.conf.urls import url
from exams import views
from exams.views import SubjectAutocomplete
from academics.views import ClassAutocomplete
from dal import autocomplete

urlpatterns = [

    
    url(r'^class-autocomplete/$', ClassAutocomplete.as_view(),name='class_autocomplete'),
	url(r'^subject-autocomplete/$',SubjectAutocomplete.as_view(),name='subject_autocomplete'), 

    url(r'^create/exam/$', views.create_exam, name='create_exam'),
    url(r'^view/exam/(?P<pk>.*)/$', views.view_exam, name='view_exam'),
    url(r'^edit/exam/(?P<pk>.*)/$', views.edit_exam, name='edit_exam'),
    url(r'^delete/exam/(?P<pk>.*)/$', views.delete_exam, name='delete_exam'),
    url(r'^delete/selected-exams/$', views.delete_selected_exams, name='delete_selected_exams'),
    url(r'^exams/$', views.exams, name='exams'),
    url(r'^exam/(?P<pk>.*)/$', views.exam, name='exam'),

    url(r'^list-class-and-division-for-exams/$', views.list_class_and_division_for_exams, name='list_class_and_division_for_exams'),

    url(r'^create/evaluation/(?P<pk>.*)/$', views.create_evaluation, name='create_evaluation'),
    url(r'^evaluations/(?P<pk>.*)/$', views.evaluations, name='evaluations'),
    url(r'^view-evaluation/(?P<pk>.*)/$', views.view_evaluation, name='view_evaluation'),
    url(r'^edit/evaluation/(?P<pk>.*)/$', views.edit_evaluation, name='edit_evaluation'),
    url(r'^delete/evaluation/(?P<pk>.*)/$', views.delete_evaluation, name='delete_evaluation'),
    url(r'^list-divisions-for-evaluation-results/(?P<pk>.*)/$', views.list_divisions_for_evaluation_results, name='list_divisions_for_evaluation_results'),
    url(r'^create-exam-result/(?P<pk>[0-9a-f-]+)/division/(?P<division_pk>[0-9a-f-]+)/$', views.create_exam_result, name='create_exam_result'),
    url(r'^edit/exam-result/(?P<pk>.*)/$', views.edit_exam_result, name='edit_exam_result'),
    url(r'^delete/exam-result/(?P<pk>.*)/$', views.delete_exam_result, name='delete_exam_result'),
    url(r'^list-divisions-for-view-results/(?P<pk>.*)/$', views.list_divisions_for_view_results, name='list_divisions_for_view_results'), 
    url(r'^view/exam-result/(?P<pk>.*)/$', views.view_exam_result, name='view_exam_result'),
    url(r'^exam-results/(?P<pk>[0-9a-f-]+)/division/(?P<division_pk>[0-9a-f-]+)/$', views.exam_results, name='exam_results'),
]

institute/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.views.static import serve
from django.conf import settings
from registration.backends.default.views import RegistrationView
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', general_views.app,name='app'),

    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^app/create-college/$',general_views.create_college,name='create_college'),
    url(r'^app/switch-college/$', general_views.switch_college, name='switch_college'),
    url(r'^app/switch-theme/$', general_views.switch_theme, name='switch_theme'),
    url(r'^app/switch-batch/$', general_views.switch_batch, name='switch_batch'),

    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url(r'^academics/', include(('academics.urls', 'academics'), namespace='academics')),
    url(r'^transports/', include(('transports.urls', 'transports'), namespace='transports')),
    url(r'^main/', include(('main.urls', 'main'), namespace='main')),
    url(r'^staffs/', include(('staffs.urls', 'staffs'), namespace='staffs')),
    url(r'^finance/', include(('finance.urls', 'finance'), namespace='finance')),
    url(r'^scholarships/', include(('scholarships.urls', 'scholarships'), namespace='scholarships')),
    url(r'^task/', include(('task.urls', 'task'), namespace='task')),

    url(r'^exams/', include(('exams.urls', 'exams'), namespace='exams')),
    url(r'^enquiries/', include(('enquiries.urls', 'enquiries'), namespace='enquiries')),
    url(r'^store/product/', include(('store.product.urls', 'store_product'), namespace='store_product')),
    url(r'^pta/', include(('pta.urls', 'pta'), namespace='pta')),
    url(r'^notifications/', include(('notifications.urls', 'notifications'), namespace='notifications')),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

main/exams/urls.py
from django.conf.urls import url
from exams import views
from exams.views import SubjectAutocomplete
from academics.views import ClassAutocomplete
from dal import autocomplete

urlpatterns = [

    
    url(r'^class-autocomplete/$', ClassAutocomplete.as_view(),name='class_autocomplete'),
	url(r'^subject-autocomplete/$',SubjectAutocomplete.as_view(),name='subject_autocomplete'), 

    url(r'^create/exam/$', views.create_exam, name='create_exam'),
    url(r'^view/exam/(?P<pk>.*)/$', views.view_exam, name='view_exam'),
    url(r'^edit/exam/(?P<pk>.*)/$', views.edit_exam, name='edit_exam'),
    url(r'^delete/exam/(?P<pk>.*)/$', views.delete_exam, name='delete_exam'),
    url(r'^delete/selected-exams/$', views.delete_selected_exams, name='delete_selected_exams'),
    url(r'^exams/$', views.exams, name='exams'),
    url(r'^exam/(?P<pk>.*)/$', views.exam, name='exam'),

    url(r'^list-class-and-division-for-exams/$', views.list_class_and_division_for_exams, name='list_class_and_division_for_exams'),

    url(r'^create/evaluation/(?P<pk>.*)/$', views.create_evaluation, name='create_evaluation'),
    url(r'^evaluations/(?P<pk>.*)/$', views.evaluations, name='evaluations'),
    url(r'^view-evaluation/(?P<pk>.*)/$', views.view_evaluation, name='view_evaluation'),
    url(r'^edit/evaluation/(?P<pk>.*)/$', views.edit_evaluation, name='edit_evaluation'),
    url(r'^delete/evaluation/(?P<pk>.*)/$', views.delete_evaluation, name='delete_evaluation'),
    url(r'^list-divisions-for-evaluation-results/(?P<pk>.*)/$', views.list_divisions_for_evaluation_results, name='list_divisions_for_evaluation_results'),
    url(r'^create-exam-result/(?P<pk>[0-9a-f-]+)/division/(?P<division_pk>[0-9a-f-]+)/$', views.create_exam_result, name='create_exam_result'),
    url(r'^edit/exam-result/(?P<pk>.*)/$', views.edit_exam_result, name='edit_exam_result'),
    url(r'^delete/exam-result/(?P<pk>.*)/$', views.delete_exam_result, name='delete_exam_result'),
    url(r'^list-divisions-for-view-results/(?P<pk>.*)/$', views.list_divisions_for_view_results, name='list_divisions_for_view_results'), 
    url(r'^view/exam-result/(?P<pk>.*)/$', views.view_exam_result, name='view_exam_result'),
    url(r'^exam-results/(?P<pk>[0-9a-f-]+)/division/(?P<division_pk>[0-9a-f-]+)/$', views.exam_results, name='exam_results'),
]

pta/urls.py
from django.conf.urls import url
from pta import views
from academics.views import DivisionAutocomplete, ClassAutocomplete
from dal import autocomplete


urlpatterns = [
    url(r'^class-autocomplete/$', ClassAutocomplete.as_view(),name='class_autocomplete'),
	url(r'^division-autocomplete/$',DivisionAutocomplete.as_view(),name='division_autocomplete'),

    url(r'^get-divisions/$', views.get_divisions, name='get_divisions'),
    url(r'^get-semesters/$', views.get_semesters, name='get_semesters'),

    url(r'^ptas/$', views.ptas, name='ptas'),
    url(r'^create/pta/$', views.create_pta, name='create_pta'),
    url(r'^pta/(?P<pk>.*)/$', views.pta, name='pta'),
    url(r'^edit/pta/(?P<pk>.*)/$', views.edit_pta, name='edit_pta'),
    url(r'^delete/pta/(?P<pk>.*)/$', views.delete_pta, name='delete_pta'),

    url(r'^create/pta-attendance/(?P<pk>.*)/$', views.create_pta_attendance, name='create_pta_attendance'),
    url(r'^edit/pta-attendance/(?P<pk>.*)/$', views.edit_pta_attendance, name='edit_pta_attendance'),
    url(r'^pta-attendances/(?P<pk>.*)/$', views.pta_attendances, name='pta_attendances'),
    url(r'^view/pta-attendance/(?P<pk>.*)/$', views.pta_attendance, name='pta_attendance'),
    url(r'^delete/delete-pta-attendance/(?P<pk>.*)/$', views.delete_pta_attendance, name='delete_pta_attendance'),
    url(r'^show-calendar-pta-attendances/(?P<pk>.*)/$', views.show_calendar_pta_attendances, name='show_calendar_pta_attendances'),
]

users/urls.py
from django.conf.urls import  url,include
from users import views
from main import views as general_views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^view/(?P<pk>.*)/$', views.view, name='view'),
    
    url(r'^check-notification/$', views.check_notification, name='check_notification'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notification/delete/(?P<pk>.*)/$', views.delete_notification, name='delete_notification'),
    url(r'^delete-selected-notifications/$', views.delete_selected_notifications, name='delete_selected_notifications'),
    url(r'^notification/read/(?P<pk>.*)/$', views.read_notification, name='read_notification'),
    url(r'^read-selected-notifications/$', views.read_selected_notifications, name='read_selected_notifications'),
    
    url(r'^set-user-timezone/$', views.set_user_timezone, name='set_user_timezone'),
    
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^settings/update-college/$', views.update_college, name='update_college'),
    url(r'^settings/update-profile/$', views.update_profile, name='update_profile'),

    url(r'^users/$', views.users, name='users'), 
]

exams/enquiries/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from main.models import BaseModel
from django.core.validators import MinValueValidator
from decimal import Decimal
from django.utils.translation import ugettext_lazy as _


class Enquiry(BaseModel):
    student = models.ForeignKey("academics.Admission",limit_choices_to={'is_deleted': False},on_delete=models.CASCADE,blank=True,null=True)
    name = models.CharField(max_length=128,)
    email = models.EmailField(blank=True,null=True)
    phone = models.CharField(max_length=128,)
    address = models.CharField(max_length=128,)
    reason = models.CharField(max_length=128,)

    class Meta:
        db_table = 'enquiries_enquiry'
        verbose_name = _('enquiry')
        verbose_name_plural = _('enquiries')

    def __str__(self):
        return self.name

exams/enquiries/views.py
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from enquiries.models import Enquiry
from academics.models import Admission
from enquiries.forms import EnquiryForm
from django.utils.translation import ugettext_lazy as _
from main.functions import get_auto_id, generate_form_errors, get_current_role, generate_unique_id, get_admn_no, get_a_id
from users.functions import get_current_college, college_access,get_current_batch
from django.forms.formsets import formset_factory
import json
from django.forms.models import inlineformset_factory
from django.forms.widgets import TextInput, Select
from main.decorators import check_mode, ajax_required, role_required
import datetime
import xlrd
import random
from dal import autocomplete
from django.core import serializers
from decimal import Decimal
from django.db.models import Q
from django.contrib.auth.models import User, Group


class AdmissionAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        items = Admission.objects.filter(is_deleted=False)

        if self.q:
            items = items.filter(Q(auto_id__istartswith=self.q) |
                                 Q(name__istartswith=self.q)
                                )

        return items


@check_mode
@login_required
@role_required(['superadmin'])
def create_enquiry(request):
    url = reverse('enquiries:create_enquiry')
    current_college = get_current_college(request)
    current_batch = get_current_batch(request)

    if request.method == "POST":
        form = EnquiryForm(request.POST)
        if form.is_valid():             
            data = form.save(commit=False)
            auto_id = get_auto_id(Enquiry)
            data.auto_id = auto_id  
            data.creator = request.user
            data.updater = request.user
            data.college = current_college
            data.batch = current_batch
            data.a_id = get_a_id(Enquiry,request)
            data.save()

            response_data = {
                "status": "true",
                "title": "Successfully created",
                "message": "Enquiry successfully created.",
                "redirect": "true",
                "redirect_url": reverse('enquiries:enquiry', kwargs={'pk':data.pk})
                }

        else:
            message = generate_form_errors(form, formset=False)            

            response_data = {
                "status": "false",
                "stable": "true",
                "title": "Form validation error",
                "message": str(message)
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:
        form = EnquiryForm()

        context = {
            "title" : "Create Enquiry",
            "form" : form,            
            "redirect": "true",

            "is_need_select_picker" : True,
            "is_need_popup_box" : True,
            "is_need_custom_scroll_bar" : True,
            "is_need_wave_effect" : True,
            "is_need_bootstrap_growl" : True,
            "is_need_chosen_select" : True,
            "is_need_grid_system" : True,
            "is_need_datetime_picker" : True,
            "is_need_animations": True,
        }
        return render(request, 'enquiries/entry_enquiry.html', context)


@check_mode
@login_required
@role_required(['superadmin'])
def edit_enquiry(request,pk):
    instance = get_object_or_404(Enquiry.objects.filter(pk=pk,is_deleted=False))
    url = reverse('enquiries:edit_enquiry',kwargs={'pk':pk})

    if request.method == "POST":

        form = EnquiryForm(request.POST,instance=instance)

        if form.is_valid(): 

            data = form.save(commit=False)
            data.updater = request.user
            data.date_updated = datetime.datetime.now()
            data.save()

            response_data = {
                "status": "true",
                "title": "Successfully updated",
                "message": "Enquiry successfully updated.",
                "redirect": "true",
                "redirect_url": reverse('enquiries:enquiry',kwargs={"pk":pk})
                }

        else:
            message = generate_form_errors(form, formset=False)

            response_data = {
                "status": "false",
                "stable": "true",
                "title": "Form validation error",
                "message": str(message)
            }

        return HttpResponse(json.dumps(response_data), content_type='application/javascript')

    else:
        form = EnquiryForm(instance=instance)

        context = {
            "title" : "Edit Enquiry",
            "form" : form,
            "instance" : instance,
            "redirect": "true",            

            "is_need_select_picker" : True,
            "is_need_popup_box" : True,
            "is_need_custom_scroll_bar" : True,
            "is_need_wave_effect" : True,
            "is_need_bootstrap_growl" : True,
            "is_need_chosen_select" : True,
            "is_need_grid_system" : True,
            "is_need_datetime_picker" : True,
            "is_need_animations": True,
        }
        return render(request, 'enquiries/entry_enquiry.html', context)



@check_mode
@login_required
@role_required(['superadmin'])
def enquiries(request):
    instances = Enquiry.objects.filter(is_deleted=False)

    query = request.GET.get("q")
    if query:
        instances = instances.filter( Q(name__icontains=query))
        title = "Classes - %s" %query 

    context = {
        "instances" : instances,
        "title" : "Enquiries",

        "is_need_select_picker" : True,
        "is_need_popup_box" : True,
        "is_need_custom_scroll_bar" : True,
        "is_need_wave_effect" : True,
        "is_need_bootstrap_growl" : True,
        "is_need_chosen_select" : True,
        "is_need_grid_system" : True,
        "is_need_datetime_picker" : True,
        "is_need_animations": True,
    }
    return render(request, 'enquiries/enquiries.html', context)


@check_mode
@login_required
@role_required(['superadmin'])
def enquiry(request,pk):
    instance = get_object_or_404(Enquiry.objects.filter(pk=pk))

    context = {
        'title' : instance.name,
        'instance' : instance,
        "is_need_popup_box": True,
        "is_need_custom_scroll_bar": True,
        "is_need_wave_effect": True,
        "is_need_bootstrap_growl": True,
        "is_need_animations": True,
        "is_need_grid_system": True,
        "is_need_select_picker": True,
        "is_need_datetime_picker" : True
    }
    return render(request,'enquiries/enquiry.html',context)


@check_mode
@login_required
@role_required(['superadmin'])
def delete_enquiry(request,pk):
    instance = get_object_or_404(Enquiry.objects.filter(pk=pk,is_deleted=False))
    Enquiry.objects.filter(pk=pk).update(is_deleted=True,name=instance.name + "_deleted_" + str(instance.auto_id))
    
    response_data = {
        "status": "true",
        "title": "Successfully deleted",
        "message": "Enquiry successfully deleted.",
        "redirect": "true",
        "redirect_url": reverse('enquiries:enquiries')
    }

    return HttpResponse(json.dumps(response_data), content_type='application/javascript')

templates/exams/evaluations.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<section id="content" class="content-wrapper">
    <div class="action-header palette-theme {{current_theme}} bg clearfix">
        <div class="ah-label hidden-xs palette-White text">{{title}}</div>

        <div class="ah-search">
            <form method="get" action="{% url 'exams:evaluations' pk=exam_pk %}" class="ahs-input">
                <input name="q" type="text" placeholder="Start typing..." class="ahs-input">

                <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
                <input type="submit" class="hidden" />
            </form>
        </div>

        <ul class="ah-actions actions a-alt">
            <li>
                <a class="ah-search-trigger" data-ma-action="ah-search-open" href="">
                    <i class="zmdi zmdi-search"></i>
                </a>
            </li>
            <li>
                <a title="Filter" class="filter_button" href="">
                    <i class="zmdi zmdi-filter-list"></i>
                </a>
            </li>
            <li>
                <a title="Create Evaluation" href="{% url 'exams:create_evaluation' pk=exam_pk %}">
                    <i class="zmdi zmdi-plus"></i>
                </a>
            </li>
        </ul>
    </div>
    <div class="card-body">
        <div class="card">
            {% if instances %}
            <div class="row p-5 p-b-0">            
                {% for instance in instances %} 
                <div class="col-lg-4 p-r-5 p-l-15 col-md-6 col-sm-6 m-b-5">
                    <a href="{% url 'exams:view_evaluation' pk=instance.pk %}">

                        <div class="color-widget three palette-theme {{current_theme}} bg">
                            <h3 class="text-center" style="color: rgb(255, 255, 255);">{{instance.subject.name}}</h3>
                            <h4 class="text-center m-t-20 f-17" style="color: #fff;">{{instance.exam}}</h4>
                            <div class="bottom-top-section">
                                <p style="float: left" class="three">{{instance.exam_date}}</p>
                                <p style="float: right" class="three">{{instance.from_time|time:"H:i"}} - {{instance.to_time|time:"H:i"}}</p>
                                <br class="clear" />
                            </div>
                            <div class="bottom two" style="">
                                <span style="display: inline-block;float: left;" class="result">
                                    <a title="Results" href="{% url 'exams:list_divisions_for_view_results' pk=instance.pk %}">View Result</a>
                                </span>
                                
                                <span style="display: inline-block;float: right;" class="result">
                                    <a title="Create exam result" href="{% url 'exams:list_divisions_for_evaluation_results' pk=instance.pk %}">Create Result
                                           
                                    </a>
                                </span>
                                <br class="clear" />
                             </div>
                        </div>
                        <ul>
                            <li class="dropdown hidden-xs menu-one">
                                <a data-toggle="dropdown" href="" aria-expanded="false"><i class="hm-icon zmdi zmdi-more-vert"></i></a>
                                <ul class="dropdown-menu dm-icon pull-right">
                                    <li class="hidden-xs">
                                        <a href="{% url 'exams:edit_evaluation' pk=instance.pk %}"><i class="zmdi zmdi-edit"></i>Edit</a>
                                    </li>
                                    <li>
                                         <a data-id="{{instance.pk}}" href="{% url 'exams:delete_evaluation' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn" style="text-align: left;;color: #000;"><i class="zmdi zmdi-delete" ></i>Delete</a>
                                    </li>
                                </ul>
                            </li>
                        </ul> 
                    </a>
                </div>
                {% endfor %}
            </div>
            {% endif %}    
        </div>  
    </div>
</section>
<!-- content-wrapper ends -->
{% endblock %}

{% block filter_box %}
<div class="filter-box">
     <form method="get" action="{% url 'exams:evaluations' pk=exam_pk %}">
        <div class="card">
            <div class="card-header">
                <h2>Filter <small></small></h2>
                <span class="back-button-poupup palette-Cyan bg btn btn-default btn-icon-text waves-effect"><i class="zmdi zmdi-arrow-back"></i>Back</span>
            </div>
            
            <div class="card-body card-padding">
                <div class="form-group fg-line">
                    <label>Query</label>
                    <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
                </div>


               
                 <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
            </div>
         </div>
     </form>
</div>
{% endblock %}

{% block static %}
    {% load static %}
    <style>
        li.menu-one {
            position: absolute;
            top: 4px;
            right: 26px;
            color: #fff;

        }
        div.bottom.two {
            padding: 10px;
            margin-top: 20px;
        }
        p.three {
            margin-bottom: 0;
            color: #fff;
        }
        .btn:not(.btn-link) {
            box-shadow: none;
        }
        i.hm-icon{
            color: #fff !important;

        }
        li.menu-one i.zmdi{
            color: #000;

        }

        li.color-widget.three {
            position: relative;
        }
        ul {
            list-style: none;
        }
        .color-widget {
            min-height: 160px;
        }
        .color-widget h4{
            text-align: center;
        }
        .action-header {
            min-height: 0px;
        }
    </style>
{% endblock %}

templates/exams/list_exams.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<section id="content" class="content-wrapper">
    <div class="action-header palette-theme {{current_theme}} bg clearfix">
    <div class="ah-label hidden-xs palette-Black text" style="color : #fff;">{{title}}</div>

    <div class="ah-search">
        <form method="get" action="{% url 'exams:exam' pk=department_pk %}" class="ahs-input">
            <input name="q" type="text" placeholder="Start typing..." class="ahs-input">

            <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
            <input type="submit" class="hidden" />
        </form>
    </div>

    <ul class="ah-actions actions a-alt">
        <li>
            <a href="{% url 'exams:exam' pk=department_pk %}" class="ah-search-trigger" data-ma-action="ah-search-open">
                <i class="zmdi zmdi-search"></i>
            </a>
        </li>
        <li>
            <a title="Filter" class="filter_button" href="{% url 'exams:exam' pk=department_pk %}">
                <i class="zmdi zmdi-filter-list"></i>
            </a>
        </li>
        <li>
            <a title="Create Exam" href="{% url 'exams:create_exam' %}">
                <i class="zmdi zmdi-plus"></i>
            </a>
        </li>
    </ul>
</div>


    <div class="card">
        {% if instances %}
        <div class="action-header p-l-15 f-17 bgm-white clearfix m-b-0 p-b-0">
        </div>

            <div class="row p-l-20 p-r-20 p-b-20 p-t-0"> 


            {% load el_pagination_tags %}
            {% paginate 21 instances %}
            {% for instance in instances %}               
                <div class="col-lg-4 col-md-4 col-sm-3 m-b-10">
                    <a href="{% url 'exams:evaluations' pk=instance.pk %}">

                        <div class="color-widget three palette-theme {{current_theme}} bg">
                            <h3 class="text-center" style="color: #fff;">{{instance.title}}</h3>
                            <h4 class="text-center m-t-20 f-17" style="color: #fff;">{{instance.from_date}} - {{instance.to_date}}</h4>
                            <ul>
                                <li class="dropdown hidden-xs menu-one">
                                    <a data-toggle="dropdown" href="" aria-expanded="false"><i class="hm-icon zmdi zmdi-more-vert"></i></a>
                                    <ul class="dropdown-menu dm-icon pull-right">
                                        <li class="hidden-xs">
                                            <a href="{% url 'exams:edit_exam' pk=instance.pk %}"><i class="zmdi zmdi-edit"></i>Edit</a>
                                        </li>
                                         <li class="hidden-xs">
                                            <a href="{% url 'exams:create_evaluation' pk=instance.pk %}"><i class="zmdi zmdi-plus"></i>Create Evaluation</a>
                                        </li>
                                         <li class="hidden-xs">
                                            <a href="{% url 'exams:evaluations' pk=instance.pk %}"><i class="zmdi zmdi-eye"></i>View Evaluations</a>
                                        </li>
                                        <li>
                                             <a data-id="{{instance.pk}}" href="{% url 'exams:delete_exam' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn" style="text-align: left;;color: #000;"><i class="zmdi zmdi-delete" ></i>Delete</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul> 
                        </div>
                    </a>
                </div>  
            {% endfor %}

            </div>
            <!--pagination -->
            <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                {% get_pages %}
                <div class="row">
                    <div class="col-sm-6">
                        <div class="pagination">
                            {% show_pages %}
                        </div>
                    </div>
                    <div class="col-sm-6 infoBar">
                        <div class="infos">
                            Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                        </div>
                    </div>
                </div>
            </div>
            <!--pagination-->
            {% else %}
                {% include 'includes/not_found.html' %}
            {% endif %}
        
    </div>
</section>
<!-- content-wrapper ends -->
{% endblock %}

{% block filter_box %}
<div class="filter-box">
     <form method="get" action="{% url 'exams:exam' pk=department_pk %}">
        <div class="card">
            <div class="card-header">
                <h2>Filter <small></small></h2>
                <span class="back-button-poupup palette-Cyan bg btn btn-default btn-icon-text waves-effect"><i class="zmdi zmdi-arrow-back"></i>Back</span>
            </div>
            
            <div class="card-body card-padding">
                <div class="form-group fg-line">
                    <label>Query</label>
                    <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
                </div>


               
                 <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
            </div>
         </div>
     </form>
</div>
{% endblock %}

{% block static %}
    {% load static %}
    <style>
        li.menu-one {
            position: absolute;
            top: 4px;
            right: 26px;
            color: #fff;

        }
        .btn:not(.btn-link) {
            box-shadow: none;
        }
        i.hm-icon{
            color: #fff !important;

        }
        li.menu-one i.zmdi{
            color: #000;

        }

        li.color-widget.three {
            position: relative;
        }
        ul {
            list-style: none;
        }
        .color-widget {
            min-height: 160px;
        }
        .color-widget h4{
            text-align: center;
        }
        .action-header {
            min-height: 0px;
        }
    </style>
{% endblock %}