institute/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.views.static import serve
from django.conf import settings
from registration.backends.default.views import RegistrationView
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', general_views.app,name='app'),

    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^app/create-college/$',general_views.create_college,name='create_college'),
    url(r'^app/switch-college/$', general_views.switch_college, name='switch_college'),
    url(r'^app/switch-theme/$', general_views.switch_theme, name='switch_theme'),
    url(r'^app/switch-batch/$', general_views.switch_batch, name='switch_batch'),

    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url(r'^academics/', include(('academics.urls', 'academics'), namespace='academics')),
    url(r'^transports/', include(('transports.urls', 'transports'), namespace='transports')),
    url(r'^main/', include(('main.urls', 'main'), namespace='main')),
    url(r'^staffs/', include(('staffs.urls', 'staffs'), namespace='staffs')),
    url(r'^finance/', include(('finance.urls', 'finance'), namespace='finance')),
    url(r'^scholarships/', include(('scholarships.urls', 'scholarships'), namespace='scholarships')),
    url(r'^task/', include(('task.urls', 'task'), namespace='task')),

    url(r'^exams/', include(('exams.urls', 'exams'), namespace='exams')),
    url(r'^enquiries/', include(('enquiries.urls', 'enquiries'), namespace='enquiries')),
    url(r'^store/product/', include(('store.product.urls', 'store_product'), namespace='store_product')),
    url(r'^pta/', include(('pta.urls', 'pta'), namespace='pta')),
    url(r'^notifications/', include(('notifications.urls', 'notifications'), namespace='notifications')),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

pta/urls.py
from django.conf.urls import url
from pta import views
from academics.views import DivisionAutocomplete, ClassAutocomplete
from dal import autocomplete


urlpatterns = [
    url(r'^class-autocomplete/$', ClassAutocomplete.as_view(),name='class_autocomplete'),
	url(r'^division-autocomplete/$',DivisionAutocomplete.as_view(),name='division_autocomplete'),

    url(r'^get-divisions/$', views.get_divisions, name='get_divisions'),
    url(r'^get-semesters/$', views.get_semesters, name='get_semesters'),

    url(r'^ptas/$', views.ptas, name='ptas'),
    url(r'^create/pta/$', views.create_pta, name='create_pta'),
    url(r'^pta/(?P<pk>.*)/$', views.pta, name='pta'),
    url(r'^edit/pta/(?P<pk>.*)/$', views.edit_pta, name='edit_pta'),
    url(r'^delete/pta/(?P<pk>.*)/$', views.delete_pta, name='delete_pta'),

    url(r'^create/pta-attendance/(?P<pk>.*)/$', views.create_pta_attendance, name='create_pta_attendance'),
    url(r'^edit/pta-attendance/(?P<pk>.*)/$', views.edit_pta_attendance, name='edit_pta_attendance'),
    url(r'^pta-attendances/(?P<pk>.*)/$', views.pta_attendances, name='pta_attendances'),
    url(r'^view/pta-attendance/(?P<pk>.*)/$', views.pta_attendance, name='pta_attendance'),
    url(r'^delete/delete-pta-attendance/(?P<pk>.*)/$', views.delete_pta_attendance, name='delete_pta_attendance'),
    url(r'^show-calendar-pta-attendances/(?P<pk>.*)/$', views.show_calendar_pta_attendances, name='show_calendar_pta_attendances'),
]

scholarships/urls.py
from django.conf.urls import url
from scholarships import views
from scholarships.views import ScholarshipCategoryAutocomplete, ScholarshipAutocomplete


urlpatterns = [ 
    url(r'^scholarship-autocomplete/$', ScholarshipAutocomplete.as_view(),name='scholarship_autocomplete'),
    url(r'^scholarship-category-autocomplete/$', ScholarshipCategoryAutocomplete.as_view(),name='scholarship_category_autocomplete'),

    url(r'^scholarship-categories/$', views.scholarship_categories, name='scholarship_categories'),
    url(r'^create/scholarship-category/$', views.create_scholarship_category, name='create_scholarship_category'),
    url(r'^scholarship-category/(?P<pk>.*)/$', views.scholarship_category, name='scholarship_category'),
    url(r'^edit/scholarship-category/(?P<pk>.*)/$', views.edit_scholarship_category, name='edit_scholarship_category'),
    url(r'^delete/scholarship-category/(?P<pk>.*)/$', views.delete_scholarship_category, name='delete_scholarship_category'),

    url(r'^scholarships/$', views.scholarships, name='scholarships'),
    url(r'^create/scholarship/$', views.create_scholarship, name='create_scholarship'),
    url(r'^scholarship/(?P<pk>.*)/$', views.scholarship, name='scholarship'),
    url(r'^edit/scholarship/(?P<pk>.*)/$', views.edit_scholarship, name='edit_scholarship'),
    url(r'^delete/scholarship/(?P<pk>.*)/$', views.delete_scholarship, name='delete_scholarship'),

    url(r'^scholarship-applications/$', views.scholarship_applications, name='scholarship_applications'),
    url(r'^create/scholarship-application/$', views.create_scholarship_application, name='create_scholarship_application'),
    url(r'^scholarship-application/(?P<pk>.*)/$', views.scholarship_application, name='scholarship_application'),
    url(r'^edit/scholarship-application/(?P<pk>.*)/$', views.edit_scholarship_application, name='edit_scholarship_application'),
    url(r'^delete/scholarship-application/(?P<pk>.*)/$', views.delete_scholarship_application, name='delete_scholarship_application'),
    ]

staffs/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from staffs import views
from staffs.views import StaffAutocomplete, DesignationAutocomplete



urlpatterns = [ 
    url(r'^staff-autocomplete/$',StaffAutocomplete.as_view(),name='staffs_autocomplete'), 
    url(r'^designation-autocomplete/$',DesignationAutocomplete.as_view(create_field='name'),name='designation_autocomplete'),                         

	url(r'^staff/create-enquiry/$',views.create_staff,name='create_staff'),
    url(r'^staff/view/$',views.staffs,name='staffs'),
    url(r'^staff/view/(?P<pk>.*)/$',views.staff,name='staff'),
    url(r'^staff/edit/(?P<pk>.*)/$',views.edit_staff,name='edit_staff'),
    url(r'^staff/delete/(?P<pk>.*)/$',views.delete_staff,name='delete_staff'),
    url(r'^delete-selected-staffs/$', views.delete_selected_staffs, name='delete_selected_staffs'),   
    
    url(r'^staff-salary/create/$',views.create_staff_salary,name='create_staff_salary'),
    url(r'^staff-salaries/view/$',views.staff_salaries,name='staff_salaries'),
    url(r'^staff-salary/view/(?P<pk>.*)/$',views.staff_salary,name='staff_salary'),
    url(r'^staff-salary/edit/(?P<pk>.*)/$',views.edit_staff_salary,name='edit_staff_salary'),
    url(r'^staff-salary/delete/(?P<pk>.*)/$',views.delete_staff_salary,name='delete_staff_salary'),
    url(r'^delete-selected-staff-salaries/$', views.delete_selected_staff_salaries, name='delete_selected_staff_salaries'), 

    url(r'^staff-designation/create/$',views.create_designation,name='create_designation'),
    url(r'^staff-designations/view/$',views.designations,name='designations'),
    url(r'^staff-designation/view/(?P<pk>.*)/$',views.designation,name='designation'),
    url(r'^staff-designation/edit/(?P<pk>.*)/$',views.edit_designation,name='edit_designation'),
    url(r'^staff-designation/delete/(?P<pk>.*)/$',views.delete_designation,name='delete_designation'),
    url(r'^delete-selected-designations/$', views.delete_selected_designations, name='delete_selected_designations'), 

    url(r'^get-salary/$',views.get_salary,name='get_salary'),

    url(r'^staff-qualification/create/$',views.create_qualification,name='create_qualification'),
    url(r'^staff-qualifications/view/$',views.qualifications,name='qualifications'),
    url(r'^staff-qualification/view/(?P<pk>.*)/$',views.qualification,name='qualification'),
    url(r'^staff-qualification/edit/(?P<pk>.*)/$',views.edit_qualification,name='edit_qualification'),
    url(r'^staff-qualification/delete/(?P<pk>.*)/$',views.delete_qualification,name='delete_qualification'),

    url(r'^show-calendar-attendances/$',views.show_calendar_attendances,name='show_calendar_attendances'),
    url(r'^create-staff-attendance/$',views.create_staff_attendance,name='create_staff_attendance'),
    url(r'^edit/staff-attendance/(?P<pk>.*)/$', views.edit_staff_attendance, name='edit_staff_attendance'),
    url(r'^staff-attendances/$', views.staff_attendances, name='staff_attendances'),
    url(r'^view/staff-attendance/(?P<pk>.*)/$', views.staff_attendance, name='staff_attendance'),
    url(r'^delete/delete-staff-attendance/(?P<pk>.*)/$', views.delete_staff_attendance, name='delete_staff_attendance'),
    url(r'^staff/subject/(?P<pk>.*)/$',views.create_staff_subjects,name='create_staff_subjects'),

    url(r'^staff/subject-list/$',views.get_subject_details,name='get_subject_details'),
    url(r'^staff/staff-followups/(?P<pk>.*)/$',views.staff_follow_ups,name='staff_follow_ups'),


]

scholarships/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from main.models import BaseModel
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MinValueValidator
from decimal import Decimal


STATUS = (
    ('approved','Approved'),
    ('cancelled','Cancelled')
)

class ScholarshipCategory(BaseModel):
    name = models.CharField(max_length=128)

    class Meta:
        db_table = 'scholarship_categories'
        verbose_name = _('ScholarshipCategory')
        verbose_name_plural = _('ScholarshipCategories')
        ordering = ('name',)

    def __str__(self):
        return self.name


class Scholarship(BaseModel):
    title = models.CharField(max_length=128)  
    amount = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True, validators=[MinValueValidator(Decimal('0.00'))])
    from_date = models.DateField()
    to_date = models.DateField()
    category = models.ForeignKey("scholarships.ScholarshipCategory",limit_choices_to={'is_deleted': False},on_delete=models.CASCADE)

    class Meta:
        db_table = 'scholarship_scholarship'
        verbose_name = _('Scholarship')
        verbose_name_plural = _('Scholarships')
        ordering = ('title',)

    def __str__(self):
        return self.title


class ScholarshipApplication(BaseModel):
    student = models.CharField(max_length=128)
    date = models.DateField() 
    scholarship_name = models.ForeignKey("scholarships.Scholarship",limit_choices_to={'is_deleted': False},on_delete=models.CASCADE)
    status = models.CharField(max_length=128,choices=STATUS)

    class Meta:
        db_table = 'scholarship_application'
        verbose_name = _('Scholarship Application')
        verbose_name_plural = _('Scholarship Applications')
        ordering = ('scholarship_name',)

    def __str__(self):
        return self.scholarship_name

scholarships/forms.py
from django import forms
from django.forms.widgets import TextInput, Select, Textarea, HiddenInput
from scholarships.models import ScholarshipCategory, Scholarship, ScholarshipApplication
from django.utils.translation import ugettext_lazy as _
from dal import autocomplete
from decimal import Decimal


class ScholarshipCategoryForm(forms.ModelForm):
    
    class Meta:
        model = ScholarshipCategory
        exclude = ['creator','updater','auto_id','is_deleted','college','a_id']
        widgets = {
            "name": TextInput(attrs = { "class": "required form-control","placeholder" : "Scholarship Category",}),
            
        }
        error_messages = {
            "name" : {
                "required" : _("Name field is required.")
            }
        }
        
        
    def clean(self):
        cleaned_data = super(ScholarshipCategoryForm, self).clean()
        return cleaned_data


class ScholarshipForm(forms.ModelForm):
    
    class Meta:
        model = Scholarship
        exclude = ['creator','updater','auto_id','is_deleted','college','a_id']
        widgets = {
            "title": TextInput(attrs = { "class": "required form-control","placeholder" : "title",}),
            "amount": TextInput(attrs = {"class": "required form-control","placeholder" : "amount",}), 
            "from_date": TextInput(attrs = {"class": "required form-control date-picker", "placeholder"  : "from_date", }),
            "to_date": TextInput(attrs = {"class": "form-control date-picker", "placeholder" : "to_date",}),
            "category": autocomplete.ModelSelect2(url='scholarships:scholarship_category_autocomplete',attrs={'data-placeholder': 'Category','data-minimum-input-length': 1},),
        }
        error_messages = {
            "title" : {
                "required" : _("title field is required.")
            },
            "amount" : {
                "required" : _("amount field is required.")
            },
            "from_date" : {
                "required" : _("from_date field is required.")
            },
            "to_date" : {
                "required" : _("to_date field is required.")
            },
            "category" : {
                "required" : _("category field is required.")
            }
        }
        
        
    def clean(self):
        cleaned_data = super(ScholarshipForm, self).clean()
        return cleaned_data


class ScholarshipApplicationForm(forms.ModelForm):
    
    class Meta:
        model = ScholarshipApplication
        exclude = ['creator','updater','auto_id','is_deleted','college','a_id']
        widgets = {
            "student": TextInput(attrs = { "class": "required form-control","placeholder" : "Student",}),
            "date": TextInput(attrs = {"class": "date-picker form-control","placeholder" : "Date",}), 
            "scholarship_name": autocomplete.ModelSelect2(url='scholarships:scholarship_autocomplete',attrs={'data-placeholder': 'Scholorship','data-minimum-input-length': 1},),
            "status": Select(attrs = {"class": "required form-control show-tick","placeholder" : "category",}),
        }
        error_messages = {
            "student" : {
                "required" : _("student field is required.")
            },
            "date" : {
                "required" : _("date field is required.")
            },
            "scholarship_name" : {
                "required" : _("scholarship_name field is required.")
            },
            "status" : {
                "required" : _("status field is required.")
            }
        }
        
        
    def clean(self):
        cleaned_data = super(ScholarshipApplicationForm, self).clean()
        return cleaned_data

templates/scholarships/entry_scholarship_category.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <section id="content">
        <div class="container">
            
            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{title}}</div>

                <div class="ah-search">
                    <form method="get" action="{% url 'staffs:designations' %}">
                        <input name="q" type="text" placeholder="Start typing..." class="ahs-input">
    
                        <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
                        <input type="submit" class="hidden" />
                    </form>
                </div>                
            </div>
            <div id="c-grid" class="clearfix" data-columns="2">
                <form class="ajax reset {% if redirect %}redirect{% endif %}" method="post" action="{{url}}">
                        {% csrf_token %}
                    <div class="card">
                        <div class="card-body card-padding">                           
                            <div class="form-group fg-line">
                                <label for="{{ form.name.id_for_label }}">
                                    {{ form.name.label }}
                                    {% if form.name.field.required %}
                                        <small class="star">*</small>
                                    {% endif %}
                                    
                                    {% if form.name.help_text %}
                                        <span data-original-title="Field Info" title="" data-content="{{ form.name.help_text }}" data-placement="left" data-toggle="popover" data-trigger="hover" class="help-text-icon zmdi zmdi-info-outline">
                                    {% endif %}
                                </label>
                                {{ form.name }}
                                
                                {% if form.name.errors %}
                                    <label class="error">{{ form.name.errors.as_text }}</label>
                                {% endif %}
                            </div>
                            
                        </div>
                    </div>
                    <div class="m-t-20">
                        <button type="submit" class="btn btn-info waves-effect">Submit</button>
                    </div>
                </form>   
            </div>
        </div>
    </section>
{% endblock %}

templates/scholarships/scholarship_applications.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <section id="content">
        <div class="container">
            <div class="c-header">
                <h2>{{title}}</h2>
            </div>

            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{title}}</div>

                <div class="ah-search">
                    <form method="get" action="{% url 'scholarships:scholarship_applications' %}" class="ahs-input">
                        <input name="q" type="text" placeholder="Start typing..." class="ahs-input">

                        <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
                        <input type="submit" class="hidden" />
                    </form>
                </div>

                <ul class="ah-actions actions a-alt">
                    <li>
                        <a href="" class="ah-search-trigger" data-ma-action="ah-search-open">
                            <i class="zmdi zmdi-search"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Filter" class="filter_button" href="">
                            <i class="zmdi zmdi-filter-list"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Create Scholarship" href="{% url 'scholarships:create_scholarship_application' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="card">

                {% if instances %}

                <div class="table-responsive">
                    <table id="data-table-basic" class="table table-striped table-vmiddle">
                        <thead>
                            <tr>
                                <th style="width:20px;"></th>
                                
                                <th>ID</th>
                                <th>student</th>
                                <th>Date</th>
                                <th>Scholarship Name</th>
                                <th>Status</th>
                                <th data-column-id="action">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% load el_pagination_tags %}
                            {% paginate 21 instances %}
                            {% for instance in instances %}
                            <tr class="check_items_row">
                                <td style="width:20px;">
                                    <div class="checkbox lgi-checkbox m-t-5">
                                        <label>
                                            <input class="check check_item" type="checkbox" value="{{instance.pk}}" name="delete_item">
                                            <i class="input-helper"></i>
                                        </label>
                                    </div>
                                </td>
                                <td><a href="{% url 'scholarships:scholarship_application' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                                <td>{{instance.student}}</td>  
                                <td>{{instance.date}}</td>  
                                <td>{{instance.scholarship_name}}</td>  
                                <td>{{instance.status}}</td>                                 
                                <td>
                                    <a href="{% url 'scholarships:scholarship_application' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                                    <a href="{% url 'scholarships:edit_scholarship_application' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                                    <a data-id="{{instance.pk}}" href="{% url 'scholarships:delete_scholarship_application' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!--pagination -->
                <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                    {% get_pages %}
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="pagination">
                                {% show_pages %}
                            </div>
                        </div>
                        <div class="col-sm-6 infoBar">
                            <div class="infos">
                                Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <!--pagination-->
                {% else %}
                    {% include 'includes/not_found.html' %}
                {% endif %}
            </div>

        </div>
    </section>
{% endblock %}

{% block filter_box %}
<div class="filter-box">
     <form method="get" action="{% url 'scholarships:scholarship_applications' %}">
        <div class="card">
            <div class="card-header">
                <h2>Filter <small></small></h2>
                <span class="back-button-poupup palette-Cyan bg white btn btn-default btn-icon-text waves-effect"><i class="zmdi zmdi-arrow-back"></i> Back</span>
            </div>

            <div class="card-body card-padding">
                <div class="form-group fg-line">
                    <label>Query</label>
                    <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
                </div>

                 <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
            </div>
         </div>
     </form>
</div>
{% endblock %}

{% block static %}
    {% load static %}
{% endblock %}

templates/scholarships/scholarship_categories.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <section id="content">
        <div class="container">
            <div class="c-header">
                <h2>{{title}}</h2>
            </div>

            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{title}}</div>

                <div class="ah-search">
                    <form method="get" action="{% url 'scholarships:scholarship_categories' %}" class="ahs-input">
                        <input name="q" type="text" placeholder="Start typing..." class="ahs-input">

                        <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
                        <input type="submit" class="hidden" />
                    </form>
                </div>

                <ul class="ah-actions actions a-alt">
                    <li>
                        <a href="" class="ah-search-trigger" data-ma-action="ah-search-open">
                            <i class="zmdi zmdi-search"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Filter" class="filter_button" href="">
                            <i class="zmdi zmdi-filter-list"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Create Customer" href="{% url 'scholarships:create_scholarship_category' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="card">

                {% if instances %}

                <div class="table-responsive">
                    <table id="data-table-basic" class="table table-striped table-vmiddle">
                        <thead>
                            <tr>
                                <th style="width:20px;"></th>
                                
                                <th>Name</th>
                                <th data-column-id="action">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% load el_pagination_tags %}
                            {% paginate 21 instances %}
                            {% for instance in instances %}
                            <tr class="check_items_row">
                                <td style="width:20px;">
                                    <div class="checkbox lgi-checkbox m-t-5">
                                        <label>
                                            <input class="check check_item" type="checkbox" value="{{instance.pk}}" name="delete_item">
                                            <i class="input-helper"></i>
                                        </label>
                                    </div>
                                </td>
                                <td><a href="{% url 'scholarships:scholarship_category' pk=instance.pk %}">{{instance.name}}</a></td>
                                <td>
                                    <a href="{% url 'scholarships:scholarship_category' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                                    <a href="{% url 'scholarships:edit_scholarship_category' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                                    <a data-id="{{instance.pk}}" href="{% url 'scholarships:delete_scholarship_category' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!--pagination -->
                <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                    {% get_pages %}
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="pagination">
                                {% show_pages %}
                            </div>
                        </div>
                        <div class="col-sm-6 infoBar">
                            <div class="infos">
                                Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <!--pagination-->
                {% else %}
                    {% include 'includes/not_found.html' %}
                {% endif %}
            </div>

        </div>
    </section>
{% endblock %}

{% block filter_box %}
<div class="filter-box">
     <form method="get" action="{% url 'scholarships:scholarship_categories' %}">
        <div class="card">
            <div class="card-header">
                <h2>Filter <small></small></h2>
                <span class="back-button-poupup palette-Cyan bg white btn btn-default btn-icon-text waves-effect"><i class="zmdi zmdi-arrow-back"></i> Back</span>
            </div>

            <div class="card-body card-padding">
                <div class="form-group fg-line">
                    <label>Query</label>
                    <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
                </div>

                 <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
            </div>
         </div>
     </form>
</div>
{% endblock %}

{% block static %}
    {% load static %}
{% endblock %}







