institute/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.views.static import serve
from django.conf import settings
from registration.backends.default.views import RegistrationView
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', general_views.app,name='app'),

    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^app/create-college/$',general_views.create_college,name='create_college'),
    url(r'^app/switch-college/$', general_views.switch_college, name='switch_college'),
    url(r'^app/switch-theme/$', general_views.switch_theme, name='switch_theme'),
    url(r'^app/switch-batch/$', general_views.switch_batch, name='switch_batch'),

    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url(r'^academics/', include(('academics.urls', 'academics'), namespace='academics')),
    url(r'^transports/', include(('transports.urls', 'transports'), namespace='transports')),
    url(r'^main/', include(('main.urls', 'main'), namespace='main')),
    url(r'^staffs/', include(('staffs.urls', 'staffs'), namespace='staffs')),
    url(r'^finance/', include(('finance.urls', 'finance'), namespace='finance')),
    url(r'^scholarships/', include(('scholarships.urls', 'scholarships'), namespace='scholarships')),
    url(r'^task/', include(('task.urls', 'task'), namespace='task')),

    url(r'^exams/', include(('exams.urls', 'exams'), namespace='exams')),
    url(r'^enquiries/', include(('enquiries.urls', 'enquiries'), namespace='enquiries')),
    url(r'^store/product/', include(('store.product.urls', 'store_product'), namespace='store_product')),
    url(r'^pta/', include(('pta.urls', 'pta'), namespace='pta')),
    url(r'^notifications/', include(('notifications.urls', 'notifications'), namespace='notifications')),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

pta/urls.py
from django.conf.urls import url
from pta import views
from academics.views import DivisionAutocomplete, ClassAutocomplete
from dal import autocomplete


urlpatterns = [
    url(r'^class-autocomplete/$', ClassAutocomplete.as_view(),name='class_autocomplete'),
	url(r'^division-autocomplete/$',DivisionAutocomplete.as_view(),name='division_autocomplete'),

    url(r'^get-divisions/$', views.get_divisions, name='get_divisions'),
    url(r'^get-semesters/$', views.get_semesters, name='get_semesters'),

    url(r'^ptas/$', views.ptas, name='ptas'),
    url(r'^create/pta/$', views.create_pta, name='create_pta'),
    url(r'^pta/(?P<pk>.*)/$', views.pta, name='pta'),
    url(r'^edit/pta/(?P<pk>.*)/$', views.edit_pta, name='edit_pta'),
    url(r'^delete/pta/(?P<pk>.*)/$', views.delete_pta, name='delete_pta'),

    url(r'^create/pta-attendance/(?P<pk>.*)/$', views.create_pta_attendance, name='create_pta_attendance'),
    url(r'^edit/pta-attendance/(?P<pk>.*)/$', views.edit_pta_attendance, name='edit_pta_attendance'),
    url(r'^pta-attendances/(?P<pk>.*)/$', views.pta_attendances, name='pta_attendances'),
    url(r'^view/pta-attendance/(?P<pk>.*)/$', views.pta_attendance, name='pta_attendance'),
    url(r'^delete/delete-pta-attendance/(?P<pk>.*)/$', views.delete_pta_attendance, name='delete_pta_attendance'),
    url(r'^show-calendar-pta-attendances/(?P<pk>.*)/$', views.show_calendar_pta_attendances, name='show_calendar_pta_attendances'),
]

staffs/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from staffs import views
from staffs.views import StaffAutocomplete, DesignationAutocomplete



urlpatterns = [ 
    url(r'^staff-autocomplete/$',StaffAutocomplete.as_view(),name='staffs_autocomplete'), 
    url(r'^designation-autocomplete/$',DesignationAutocomplete.as_view(create_field='name'),name='designation_autocomplete'),                         

	url(r'^staff/create-enquiry/$',views.create_staff,name='create_staff'),
    url(r'^staff/view/$',views.staffs,name='staffs'),
    url(r'^staff/view/(?P<pk>.*)/$',views.staff,name='staff'),
    url(r'^staff/edit/(?P<pk>.*)/$',views.edit_staff,name='edit_staff'),
    url(r'^staff/delete/(?P<pk>.*)/$',views.delete_staff,name='delete_staff'),
    url(r'^delete-selected-staffs/$', views.delete_selected_staffs, name='delete_selected_staffs'),   
    
    url(r'^staff-salary/create/$',views.create_staff_salary,name='create_staff_salary'),
    url(r'^staff-salaries/view/$',views.staff_salaries,name='staff_salaries'),
    url(r'^staff-salary/view/(?P<pk>.*)/$',views.staff_salary,name='staff_salary'),
    url(r'^staff-salary/edit/(?P<pk>.*)/$',views.edit_staff_salary,name='edit_staff_salary'),
    url(r'^staff-salary/delete/(?P<pk>.*)/$',views.delete_staff_salary,name='delete_staff_salary'),
    url(r'^delete-selected-staff-salaries/$', views.delete_selected_staff_salaries, name='delete_selected_staff_salaries'), 

    url(r'^staff-designation/create/$',views.create_designation,name='create_designation'),
    url(r'^staff-designations/view/$',views.designations,name='designations'),
    url(r'^staff-designation/view/(?P<pk>.*)/$',views.designation,name='designation'),
    url(r'^staff-designation/edit/(?P<pk>.*)/$',views.edit_designation,name='edit_designation'),
    url(r'^staff-designation/delete/(?P<pk>.*)/$',views.delete_designation,name='delete_designation'),
    url(r'^delete-selected-designations/$', views.delete_selected_designations, name='delete_selected_designations'), 

    url(r'^get-salary/$',views.get_salary,name='get_salary'),

    url(r'^staff-qualification/create/$',views.create_qualification,name='create_qualification'),
    url(r'^staff-qualifications/view/$',views.qualifications,name='qualifications'),
    url(r'^staff-qualification/view/(?P<pk>.*)/$',views.qualification,name='qualification'),
    url(r'^staff-qualification/edit/(?P<pk>.*)/$',views.edit_qualification,name='edit_qualification'),
    url(r'^staff-qualification/delete/(?P<pk>.*)/$',views.delete_qualification,name='delete_qualification'),

    url(r'^show-calendar-attendances/$',views.show_calendar_attendances,name='show_calendar_attendances'),
    url(r'^create-staff-attendance/$',views.create_staff_attendance,name='create_staff_attendance'),
    url(r'^edit/staff-attendance/(?P<pk>.*)/$', views.edit_staff_attendance, name='edit_staff_attendance'),
    url(r'^staff-attendances/$', views.staff_attendances, name='staff_attendances'),
    url(r'^view/staff-attendance/(?P<pk>.*)/$', views.staff_attendance, name='staff_attendance'),
    url(r'^delete/delete-staff-attendance/(?P<pk>.*)/$', views.delete_staff_attendance, name='delete_staff_attendance'),
    url(r'^staff/subject/(?P<pk>.*)/$',views.create_staff_subjects,name='create_staff_subjects'),

    url(r'^staff/subject-list/$',views.get_subject_details,name='get_subject_details'),
    url(r'^staff/staff-followups/(?P<pk>.*)/$',views.staff_follow_ups,name='staff_follow_ups'),


]

users/urls.py
from django.conf.urls import  url,include
from users import views
from main import views as general_views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^view/(?P<pk>.*)/$', views.view, name='view'),
    
    url(r'^check-notification/$', views.check_notification, name='check_notification'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notification/delete/(?P<pk>.*)/$', views.delete_notification, name='delete_notification'),
    url(r'^delete-selected-notifications/$', views.delete_selected_notifications, name='delete_selected_notifications'),
    url(r'^notification/read/(?P<pk>.*)/$', views.read_notification, name='read_notification'),
    url(r'^read-selected-notifications/$', views.read_selected_notifications, name='read_selected_notifications'),
    
    url(r'^set-user-timezone/$', views.set_user_timezone, name='set_user_timezone'),
    
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^settings/update-college/$', views.update_college, name='update_college'),
    url(r'^settings/update-profile/$', views.update_profile, name='update_profile'),

    url(r'^users/$', views.users, name='users'), 
]

pta/models.py
import uuid
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MinValueValidator
from decimal import Decimal
import datetime
from main.models import BaseModel


WEEKDAY_CHOICES = (
    ('monday','MONDAY'),
    ('tuesday','TUESDAY'),
    ('wednesday','WEDNESDAY'),
    ('thursday','THURSDAY'),
    ('friday','FRIDAY'),
    ('saturday','SATURDAY')
)


class Pta(BaseModel):
    student_batch = models.ForeignKey("main.Batch",limit_choices_to={'is_deleted': False},on_delete=models.CASCADE)
    department = models.ForeignKey("academics.Department",limit_choices_to={'is_deleted': False},on_delete=models.CASCADE)
    sub_division = models.ForeignKey("academics.SubDivision",blank=True,null=True,limit_choices_to={'is_deleted': False},on_delete=models.CASCADE)
    semester = models.ForeignKey("academics.Semester",blank=True,null=True,limit_choices_to={'is_deleted': False},on_delete=models.CASCADE)
    date = models.DateField()

    class Meta:
        db_table = 'pta'
        verbose_name = 'pta'
        verbose_name_plural = 'pta'
        ordering = ('date',)

    def __str__(self):
        return self.department.name


class PtaAttendance(BaseModel):
    pta = models.ForeignKey("pta.Pta",on_delete=models.CASCADE)
    admission= models.ForeignKey("academics.Admission",on_delete=models.CASCADE)
    date = models.DateField()
    weekday = models.CharField(max_length=128,choices=WEEKDAY_CHOICES)
    department= models.ForeignKey("academics.Department",on_delete=models.CASCADE)
    sub_division = models.ForeignKey("academics.SubDivision",on_delete=models.CASCADE)
    is_present = models.BooleanField(default=True)
    remarks = models.TextField(blank=True,null=True)

    is_deleted = models.BooleanField(default=False)

    class Meta:
        db_table = 'pta_attendance'
        verbose_name = _('pta attendance')
        verbose_name_plural = _('pta attendances')
        ordering = ('date',)

    def __str__(self):
        return self.date

pta/forms.py
from django import forms
from django.forms.widgets import TextInput, Textarea, HiddenInput, CheckboxInput, EmailInput, Select
from exams.models import Exam, Evaluation, ExamResult
from academics.models import Department, SubDivision
from pta.models import PtaAttendance, Pta
from django.utils.translation import ugettext_lazy as _
from dal import autocomplete


class PTAForm(forms.ModelForm):
    
    class Meta:
        model = Pta
        exclude = ['creator','updater','auto_id','is_deleted','college','a_id','student_batch']
        widgets = {
            'department': autocomplete.ModelSelect2(url='academics:department_autocomplete',attrs={'data-placeholder': 'Department','data-minimum-input-length': 0},),
            'sub_division': Select(attrs={"class":"form-control","placeholder":"Division Wise"}),
            'semester': Select(attrs={"class":"form-control","placeholder":"Semester wise"}),
            'date': TextInput(attrs={"class":"datepicker form-control","placeholder":"Date"})
        }


class PtaAttendanceMaleForm(forms.ModelForm):

    admission_name = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','disabled':'disabled'}))
    class Meta:
        model = PtaAttendance
        exclude = ['creator','updater','auto_id','department','sub_division','is_deleted','date','weekday','absent_days_count','college','a_id','pta']
        widgets = {
            'admission' : HiddenInput(),
            "reason": TextInput(
                attrs = {
                    "class": "form-control",
                }
            ),
        }
        error_messages = {
            "admission" : {
                    "required" : _("Admission field is required.")
                },
        }


class PtaAttendanceFemaleForm(forms.ModelForm):

    admission_name = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','disabled':'disabled'}))
    class Meta:
        model = PtaAttendance
        exclude = ['creator','updater','auto_id','department','sub_division','is_deleted','date','weekday','absent_days_count','college','a_id','pta']
        widgets = {
            'admission' : HiddenInput(),
            "reason": TextInput(
                attrs = {
                    "class": "form-control",
                }
            ),
        }
        error_messages = {
            "admission" : {
                    "required" : _("Admission field is required.")
                },
        }


class PtaAttendanceDateForm(forms.ModelForm):

    admission_name = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','disabled':'disabled'}))
    class Meta:
        model = PtaAttendance
        exclude = ['creator','updater','auto_id','department','sub_division','is_deleted','admission','is_present','absent_days_count','college','a_id','pta']

        widgets = {
                "date": TextInput(
                    attrs = {
                        "class": "required form-control date-picker",
                        "placeholder" : " Date ",
                    }
                ),
                "weekday": Select(
                    attrs = {
                        "class": "required form-control selectpicker",
                    }
                )
            }
        error_messages = {
                "date" : {
                    "required" : _("Date field is required.")
                },
                "weekday" : {
                    "required" : _("Period field is required.")
                },
            }

class PtaAttendanceForm(forms.ModelForm):

    admission_name = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','disabled':'disabled'}))
    class Meta:
        model = PtaAttendance
        exclude = ['creator','updater','auto_id','department','sub_division','is_deleted','date','weekday','absent_days_count','college','a_id','pta']
        widgets = {
            'admission' : HiddenInput(),
            "reason": TextInput(attrs = {"class": "form-control"}),
            "remarks": TextInput(attrs = {"class": "form-control"}),
        }
        error_messages = {
            "admission" : {
                    "required" : _("Admission field is required.")
                },
        }


class PtaAttendanceEditForm(forms.ModelForm):

    admission_name = forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control','disabled':'disabled'}))
    class Meta:
        model = PtaAttendance
        exclude = ['creator','admission','updater','auto_id','department','sub_division','is_deleted','date','weekday','absent_days_count','college','a_id','pta']
        widgets = {
            "reason": TextInput(
                attrs = {
                    "class": "form-control",
                }
            ),
            "remarks": TextInput(
                attrs = {
                    "class": "form-control",
                }
            ),
        }
        error_messages = {

        }

templates/pta/entry_pta.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <section id="content">
        <div class="container">

            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{title}}</div>

                <div class="ah-search">
                    <form method="get" action="{% url 'pta:ptas' %}">
                        <input name="q" type="text" placeholder="Start typing..." class="ahs-input">

                        <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
                        <input type="submit" class="hidden" />
                    </form>
                </div>
            </div>
            <div id="c-grid" class="clearfix" data-columns="2">
                <form class="ajax reset {% if redirect %}redirect{% endif %}" method="post" action="{{url}}">
                        {% csrf_token %}
                    <div class="card">
                        <div class="card-body card-padding">
                            <div class="form-group fg-line">
                                <label for="{{ form.date.id_for_label }}">
                                    {{ form.date.label }}
                                    {% if form.date.field.required %}
                                        <small class="star">*</small>
                                    {% endif %}

                                    {% if form.date.help_text %}
                                        <span data-original-title="Field Info" title="" data-content="{{ form.date.help_text }}" data-placement="left" data-toggle="popover" data-trigger="hover" class="help-text-icon zmdi zmdi-info-outline">
                                    {% endif %}
                                </label>
                                <input type="text" name="{{ form.date.name }}" value="{{instance.date}}" class="form-control date-picker" placeholder="Select Date" required id="{{ form.date.id }}">

                                {% if form.date.errors %}
                                    <label class="error">{{ form.date.errors.as_text }}</label>
                                {% endif %}
                            </div>

                            <div class="form-group fg-line">
                                <label for="{{ form.department.id_for_label }}">
                                    {{ form.department.label }}
                                </label>
                                {{ form.department }}

                            </div>

                            {% if not instance %}
                                <div class="form-group fg-line">
                                    <label style="margin-right: 5px;" for="id_is_full_division">
                                        Select all Divisions under this Department </label>
                                    <input type="checkbox" name="is_full_division" value="False" id="id_is_full_division" />
                                </div>
                            {% endif %}

                            <div class="form-group fg-line all-sub-div">
                                <label for="{{ form.sub_division.id_for_label }}">
                                    {{ form.sub_division.label }}
                                </label>
                                {{ form.sub_division }}

                            </div>

                            <div class="form-group fg-line all-sub-div">
                                <label for="{{ form.semester.id_for_label }}">
                                    {{ form.semester.label }}
                                </label>
                                {{ form.semester }}
                            </div>

                        </div>
                    </div>
                    <div class="m-t-20">
                        <button type="submit" class="btn btn-info waves-effect">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
    {% endblock %}

    {% block static %}
    {% load static %}
    <script type="text/javascript" src="{% static 'js/moment-precise-range.js' %}"></script>
    <script>

        $(document).ready(function(){
            $('input[type=text]').focus(function () {
                $(this).select();
            });

            $(document).on('change, focusout', '#id_start_date, #id_end_date', function(){
                Duration();
            });

            var dept = $('#id_department').val();
            showDivisions(dept);

            var sub_div = $('#id_sub_division').val();
            showSemesters(sub_div);
        });

        $(document).on('change','#id_is_full_division',function(){
            var $this = $(this);
	        if ($this.is(':checked')){
                $(".all-sub-div").hide();
	            $(".general").show();
                $this.val("True");
	        }else{
                $(".all-sub-div").show();
	            $(".general").hide();
                $this.val("False");
	        }
	    });

        $('#id_department').on('change', function(){
            var dept = $(this).val();
            showDivisions(dept);
        });

        $('#id_sub_division').on('change', function(){
            var sub_div = $(this).val();
            showSemesters(sub_div);
        });

        function showDivisions(dept){
            if(!dept){
                $('#id_sub_division').html('<option value="">--Select Department first--</option>');
                $('#id_sub_division').selectpicker('refresh');

            }else{

                var url = "{% url 'pta:get_divisions' %}" + "?pk=" + dept;

                $.getJSON(url, function(models) {
                    var options = '<option value="">---------</option>';
                    for (var i = 0; i < models.length; i++) {
                        options += `<option value=${models[i]['division_id']}>${models[i]['division_name']}</option>`;
                    }
                    $('#id_sub_division').html(options);
                    $('#id_sub_division').selectpicker('refresh');

                }).error(function() {
                    alert("Divisions not loaded. Please refresh page again.");
                });
            }
        }

        function showSemesters(sub_div_id){
            if(!sub_div_id){
                $('#id_semester').html('<option value="">--Select Division first--</option>');
                $('#id_semester').selectpicker('refresh');

            }else{

                var url = "{% url 'pta:get_semesters' %}" + "?pk=" + sub_div_id;

                $.getJSON(url, function(models) {
                    var options = '<option value="">---------</option>';
                    for (var i = 0; i < models.length; i++) {
                        options += `<option value=${models[i]['semester_id']}>${models[i]['semester_name']}</option>`;
                    }
                    $('#id_semester').html(options);
                    $('#id_semester').selectpicker('refresh');

                }).error(function() {
                    alert("Semesters not loaded. Please refresh page again.");
                });
            }
        }
        </script>
    {{form.media}}
{% endblock %}

templates/pta/pta.html
{% extends "base.html" %}
{% load i18n %}

{% load users_template_tags %}
{% load tz %}
{% block content %}
    <section id="content">
        <div class="container">
            <div class="c-header">
                <h2>PTA of {{instance.date}}</h2>
            </div>

            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{instance.date}}</div>

                <ul class="ah-actions actions a-alt">
                    <li>
                        <a title="Create PTA Attendance" href="{% url 'pta:create_pta_attendance' pk=instance.pk %}">
                            <i class="zmdi zmdi-accounts-add"></i>
                        </a>
                    </li>
                    <li>
                        <a title="View Attendance" href="{% url 'pta:show_calendar_pta_attendances' pk=instance.pk %}">
                            <i class="zmdi zmdi-account-box-mail"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Create PTA" href="{% url 'pta:create_pta' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Edit PTA" href="{% url 'pta:edit_pta' pk=instance.pk %}">
                            <i class="zmdi zmdi-edit"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Delete PTA" data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href="{% url 'pta:delete_pta' pk=instance.pk %}" class="action-button redirect">
                            <i class="zmdi zmdi-delete"></i>
                        </a>
                    </li>
                </ul>
            </div>

            <div id="c-grid" class="clearfix" data-columns="2">
                <div class="card">
                    <div class="card-header">
                        <h2>Subject Info <small></small></h2>
                    </div>

                    <div class="card-body">
                        <div class="list-group lg-alt c-overflow">
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Date</div>
                                    <small class="lgi-text">{{instance.date}}</small>
                                </div>
                            </div>
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Department and Division</div>
                                    <small class="lgi-text">{{instance.sub_division}}</small>
                                </div>
                            </div>
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Semester</div>
                                    <small class="lgi-text">{{instance.semester}}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-header">
                        <h2>Created &amp; Updated <small></small></h2>
                    </div>

                    <div class="card-body">
                        <div class="list-group lg-alt c-overflow">
                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Date Added</div>
                                    <small class="lgi-text">{{instance.date_added|timezone:user_time_zone}}</small>
                                </div>
                            </div>

                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Date Updated</div>
                                    <small class="lgi-text">{{instance.date_updated|timezone:user_time_zone}}</small>
                                </div>
                            </div>

                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Created User</div>
                                    <small class="lgi-text"><a href="{% url 'users:view' pk=instance.creator.username %}">{{instance.creator.username|get_user_name}}</a></small>
                                </div>
                            </div>

                            <div class="list-group-item media">
                                <div class="media-body">
                                    <div class="lgi-heading">Last Updated User</div>
                                    <small class="lgi-text"><a href="{% url 'users:view' pk=instance.updater.username %}">{{instance.updater.username|get_user_name}}</a></small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

             </div>
        </div>
    </section>
{% endblock %}

{% block static %}
    {% load static %}
{% endblock %}

templates/pta/pta_attendance_calender.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{title}}{% endblock %}

{% load static %}

{% block content %}
    <section id="content" class="content-wrapper">
        <div class="container">
            <div class="c-header">
                <h2>Calendar</h2>
            </div>    

            <div id="calendar" class="card"></div>
        </div>
    </section>
{% endblock %}

{% block static %}
    {% load static %}
   
    <script type="text/javascript">
        $(document).ready(function() {
            $('#calendar').fullCalendar({
                dayClick: function(date, jsEvent, view) {
                    var redirect_url = "{% url 'pta:pta_attendances' pk=pta.pk %}?date=" + date.format('MM/DD/YYYY');
                    window.location.href = redirect_url;
                    
                }
            })
        });
    </script>
{% endblock %}