institute/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from main import views as general_views
from django.views.static import serve
from django.conf import settings
from registration.backends.default.views import RegistrationView
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', general_views.app,name='app'),

    url(r'^app/$',general_views.app,name='app'),
    url(r'^app/dashboard/$',general_views.dashboard,name='dashboard'),
    url(r'^app/create-college/$',general_views.create_college,name='create_college'),
    url(r'^app/switch-college/$', general_views.switch_college, name='switch_college'),
    url(r'^app/switch-theme/$', general_views.switch_theme, name='switch_theme'),
    url(r'^app/switch-batch/$', general_views.switch_batch, name='switch_batch'),

    url(r'^app/accounts/', include('registration.backends.default.urls')),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url(r'^academics/', include(('academics.urls', 'academics'), namespace='academics')),
    url(r'^transports/', include(('transports.urls', 'transports'), namespace='transports')),
    url(r'^main/', include(('main.urls', 'main'), namespace='main')),
    url(r'^staffs/', include(('staffs.urls', 'staffs'), namespace='staffs')),
    url(r'^finance/', include(('finance.urls', 'finance'), namespace='finance')),
    url(r'^scholarships/', include(('scholarships.urls', 'scholarships'), namespace='scholarships')),
    url(r'^task/', include(('task.urls', 'task'), namespace='task')),

    url(r'^exams/', include(('exams.urls', 'exams'), namespace='exams')),
    url(r'^enquiries/', include(('enquiries.urls', 'enquiries'), namespace='enquiries')),
    url(r'^store/product/', include(('store.product.urls', 'store_product'), namespace='store_product')),
    url(r'^pta/', include(('pta.urls', 'pta'), namespace='pta')),
    url(r'^notifications/', include(('notifications.urls', 'notifications'), namespace='notifications')),

    url(r'^media/(?P<path>.*)$', serve, { 'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, { 'document_root': settings.STATIC_FILE_ROOT}),
]

pta/urls.py
from django.conf.urls import url
from pta import views
from academics.views import DivisionAutocomplete, ClassAutocomplete
from dal import autocomplete


urlpatterns = [
    url(r'^class-autocomplete/$', ClassAutocomplete.as_view(),name='class_autocomplete'),
	url(r'^division-autocomplete/$',DivisionAutocomplete.as_view(),name='division_autocomplete'),

    url(r'^get-divisions/$', views.get_divisions, name='get_divisions'),
    url(r'^get-semesters/$', views.get_semesters, name='get_semesters'),

    url(r'^ptas/$', views.ptas, name='ptas'),
    url(r'^create/pta/$', views.create_pta, name='create_pta'),
    url(r'^pta/(?P<pk>.*)/$', views.pta, name='pta'),
    url(r'^edit/pta/(?P<pk>.*)/$', views.edit_pta, name='edit_pta'),
    url(r'^delete/pta/(?P<pk>.*)/$', views.delete_pta, name='delete_pta'),

    url(r'^create/pta-attendance/(?P<pk>.*)/$', views.create_pta_attendance, name='create_pta_attendance'),
    url(r'^edit/pta-attendance/(?P<pk>.*)/$', views.edit_pta_attendance, name='edit_pta_attendance'),
    url(r'^pta-attendances/(?P<pk>.*)/$', views.pta_attendances, name='pta_attendances'),
    url(r'^view/pta-attendance/(?P<pk>.*)/$', views.pta_attendance, name='pta_attendance'),
    url(r'^delete/delete-pta-attendance/(?P<pk>.*)/$', views.delete_pta_attendance, name='delete_pta_attendance'),
    url(r'^show-calendar-pta-attendances/(?P<pk>.*)/$', views.show_calendar_pta_attendances, name='show_calendar_pta_attendances'),
]

transports/urls.py
from django.conf.urls import url
from transports import views
from transports.views import RouteAutocomplete, VehicleAutocomplete, BoardingPointAutocomplete


urlpatterns = [
    url(r'^route-autocomplete/$',RouteAutocomplete.as_view(),name='routes_autocomplete'), 
    url(r'^vehicle-autocomplete/$',VehicleAutocomplete.as_view(),name='vehicle_autocomplete'),
    url(r'^boarding-point-autocomplete/$',BoardingPointAutocomplete.as_view(create_field='name'),name='boarding_point_autocomplete'),

    url(r'^bus-route/create-bus-route/$',views.create_bus_route,name='create_bus_route'),    
    url(r'^bus-routes/view/$',views.bus_routes,name='bus_routes'), 
    url(r'^bus-route/bus-route/view/(?P<pk>.*)/$', views.bus_route, name='bus_route'),
    url(r'^bus-route/bus-route/edit-bus_route/(?P<pk>.*)/$', views.edit_bus_route, name='edit_bus_route'),
    url(r'^bus-route/bus-route/delete/(?P<pk>.*)/$', views.delete_bus_route, name='delete_bus_route'),

    url(r'^vehicle/create-vehicle/$',views.create_vehicle,name='create_vehicle'),    
    url(r'^vehicle/view/$',views.vehicles,name='vehicles'), 
    url(r'^vehicle/vehicle/view/(?P<pk>.*)/$', views.vehicle, name='vehicle'),
    url(r'^vehicle/vehicle/edit-vehicle/(?P<pk>.*)/$', views.edit_vehicle, name='edit_vehicle'),
    url(r'^vehicle/vehicle/delete/(?P<pk>.*)/$', views.delete_vehicle, name='delete_vehicle'),
    url(r'^vehicle/delete-selected-vehicles/$', views.delete_selected_vehicles, name='delete_selected_vehicles'),

    url(r'^boarding-points/$', views.boarding_points, name='boarding_points'),
    url(r'^create/boarding-point/$', views.create_boarding_point, name='create_boarding_point'),
    url(r'^view/boarding-point/(?P<pk>.*)/$', views.view_boarding_point, name='view_boarding_point'),
    url(r'^edit/boarding-point/(?P<pk>.*)/$', views.edit_boarding_point, name='edit_boarding_point'),
    url(r'^delete/boarding-point/(?P<pk>.*)/$', views.delete_boarding_point, name='delete_boarding_point'),

    url(r'^transport/create-transport/$',views.create_transport,name='create_transport'),    
    url(r'^transport/view/$',views.transports,name='transports'), 
    url(r'^transport/transport/view/(?P<pk>.*)/$', views.transport, name='transport'),
    url(r'^transport/transport/edit-transport/(?P<pk>.*)/$', views.edit_transport, name='edit_transport'),
    url(r'^transport/transport/delete/(?P<pk>.*)/$', views.delete_transport, name='delete_transport'),
    url(r'^transport/delete-selected-transports/$', views.delete_selected_transports, name='delete_selected_transports'),

    url(r'^bus-pass/create-bus-pass/$',views.create_bus_pass,name='create_bus_pass'),    
    url(r'^bus-pass/view/$',views.bus_passes,name='bus_passes'), 
    url(r'^bus-pass/bus-pass/view/(?P<pk>.*)/$', views.bus_pass, name='bus_pass'),
    url(r'^bus-pass/bus-pass/edit-bus-pass/(?P<pk>.*)/$', views.edit_bus_pass, name='edit_bus_pass'),
    url(r'^bus-pass/bus-pass/delete/(?P<pk>.*)/$', views.delete_bus_pass, name='delete_bus_pass'),
    url(r'^bus-pass/delete-selected-bus-passes/$', views.delete_selected_bus_passes, name='delete_selected_bus_passes'),
 ]

transports/models.py
import uuid
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MinValueValidator
from decimal import Decimal
from main.models import BaseModel


CHOICE = (
    ('student','Student'),
    ('staff','Staff')
)

class BusRoute(BaseModel):
    name = models.CharField(max_length=128)
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'logistics_bus'
        verbose_name = _('bus')
        verbose_name_plural = _('buses')
        ordering = ('name',)
        
        
    def __str__(self):
        return self.name

class Vehicle(BaseModel):
    staff = models.ForeignKey("staffs.Staff",null=True,blank=True,on_delete=models.CASCADE)
    name = models.CharField(max_length=128,blank=True,null=True)
    route = models.ForeignKey("transports.BusRoute",null=True,blank=True,on_delete=models.CASCADE)
    available_seat = models.DecimalField(null=True,blank=True,decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'transports_vehicle'
        verbose_name = _('vehicle')
        verbose_name_plural = _('vehicles')
        ordering = ('name',)
        
    def __str__(self):
        return self.name

class BoardingPoint(BaseModel):
    name = models.CharField(max_length=128)
    route = models.ForeignKey("transports.BusRoute",null=True,blank=True,on_delete=models.CASCADE)
    amount = models.DecimalField(default=0,null=True,blank=True,decimal_places=2, max_digits=15, validators=[MinValueValidator(Decimal('0.00'))])
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'transports_boarding_point'
        verbose_name = _('boarding point')
        verbose_name_plural = _('boarding points')
        ordering = ('name',)
        
    def __str__(self):
        return self.name


class Transport(BaseModel):
    student = models.ForeignKey("academics.Admission",blank=True,null=True,on_delete=models.CASCADE)
    staff = models.ForeignKey("staffs.Staff",blank=True,null=True,on_delete=models.CASCADE)
    choice = models.CharField(max_length=9,choices=CHOICE,blank=True,null=True,default="student")
    boarding_point = models.ForeignKey("transports.BoardingPoint",blank=True,null=True,on_delete=models.CASCADE)
    morning_bus = models.ForeignKey("transports.Vehicle",related_name='morning_%(class)s_objects',blank=True,null=True,on_delete=models.CASCADE)
    evening_bus = models.ForeignKey("transports.Vehicle",related_name='evening_%(class)s_objects',blank=True,null=True,on_delete=models.CASCADE)
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'transports_transport'
        verbose_name = _('transport')
        verbose_name_plural = _('transports')
        ordering = ('boarding_point',)
        
    def __str__(self):
        return self.boarding_point


class BusPass(BaseModel):
    student = models.ForeignKey("academics.Admission",on_delete=models.CASCADE)
    boarding_point = models.ForeignKey("transports.BoardingPoint",on_delete=models.CASCADE)
    valid_up_to= models.DateField(blank=True,null=True)
    date_of_issue= models.DateField(blank=True,null=True)
    is_deleted = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'transports_bus_pass'
        verbose_name = _('bus_pass')
        verbose_name_plural = _('bus_passes')
        ordering = ('boarding_point',)
        
    def __str__(self):
        return self.student

transports/forms.py
from django import forms
from django.forms.widgets import TextInput,Textarea,Select
from django.utils.translation import ugettext_lazy as _
from transports.models import BusRoute, Vehicle, BoardingPoint, Transport, BusPass
from dal import autocomplete


class BusRouteForm(forms.ModelForm):
    
    class Meta:
        model=BusRoute
        exclude = ['creator','updater','auto_id','is_deleted','college','a_id']            
        widgets = {
            'name': TextInput(attrs={'class': 'required form-control','placeholder' : 'Route'}),
        }
        error_messages = {
            'name' : {
                'required' : _("Bus Route field is required."),
            },
            
        }


class VehicleForm(forms.ModelForm):
    
    class Meta:
        model=Vehicle
        exclude = ['creator','updater','auto_id','is_deleted','college','a_id']            
        widgets = {
            'name': TextInput(attrs={'class': 'required form-control','placeholder' : 'Vehicle Number'}),
            'available_seat': TextInput(attrs={'class': 'required form-control','placeholder' : 'Available Seats'}),
            'route': autocomplete.ModelSelect2(url='transports:routes_autocomplete', attrs={'data-placeholder': 'Route', 'data-minimum-input-length': 1,'class':'form-control required'},),    
            'staff': autocomplete.ModelSelect2(url='staffs:staffs_autocomplete', attrs={'data-placeholder': 'Driver', 'data-minimum-input-length': 1},),    
        }
        error_messages = {
            'name' : {
                'required' : _("Vehicle Number field is required."),
            },
            'available_seat' : {
                'required' : _("Available Seats field is required."),
            },
            'route' : {
                'required' : _("Available Route field is required."),
            },
        }

class BoardingPointForm(forms.ModelForm):
    
    class Meta:
        model = BoardingPoint
        exclude = ['creator','updater','auto_id','is_deleted','college','a_id']    
        widgets = {
            'name': TextInput(attrs={'class': 'required form-control','placeholder' : "Enter BoardingPoint",}),
            'route': autocomplete.ModelSelect2(url='transports:routes_autocomplete', attrs={'data-placeholder': 'Route', 'data-minimum-input-length': 1},),    
            "amount": TextInput(attrs={"class": "required form-control","placeholder" : "Enter the amount",})
        }
        error_messages = {
            "name" : {
                "required" : _("Name field is required.")
            },
            
        }
        help_texts = {
        }
        
    def clean(self):
        cleaned_data = super(BoardingPointForm, self).clean()
        return cleaned_data
        


class TransportForm(forms.ModelForm):
    
    class Meta:
        model=Transport
        exclude = ['creator','updater','auto_id','is_deleted','college','a_id']            
        widgets = {
            'student': autocomplete.ModelSelect2(url='academics:admission_autocomplete', attrs={'data-placeholder': 'Student', 'data-minimum-input-length': 1},),
            'staff': autocomplete.ModelSelect2(url='staffs:staffs_autocomplete', attrs={'data-placeholder': 'Staff', 'data-minimum-input-length': 1},),
            'choice': Select(attrs={'class': 'required form-control selectpicker', 'placeholder': 'Choice'}),            
            'boarding_point' : autocomplete.ModelSelect2(url='transports:boarding_point_autocomplete',attrs={'data-placeholder': 'Boarding Point','data-minimum-input-length': 1},),
            'morning_bus' : autocomplete.ModelSelect2(url='transports:vehicle_autocomplete',attrs={'data-placeholder': 'Morning Bus','data-minimum-input-length': 1},),
            'evening_bus' : autocomplete.ModelSelect2(url='transports:vehicle_autocomplete',attrs={'data-placeholder': 'Evening Bus','data-minimum-input-length': 1},),
        }
        error_messages = {
            'student' : {
                'required' : _("Student field is required."),
            },            
            'staff' : {
                'required' : _("Staff field is required."),
            },            
        }


class BusPassForm(forms.ModelForm):
    
    class Meta:
        model=BusPass
        exclude = ['creator','updater','auto_id','is_deleted','a_id','college']            
        widgets = {
            'student': autocomplete.ModelSelect2(url='academics:admission_autocomplete', attrs={'data-placeholder': 'Student', 'data-minimum-input-length': 1},),
            'boarding_point' : autocomplete.ModelSelect2(url='transports:boarding_point_autocomplete',attrs={'data-placeholder': 'Boarding Point','data-minimum-input-length': 1},),
            'date_of_issue': TextInput(attrs={'class': 'required form-control date-picker','placeholder' : 'Date of Issue'}),
            'valid_up_to': TextInput(attrs={'class': 'required form-control date-picker','placeholder' : 'Valid Up to'}),
        }
        error_messages = {
            'student' : {
                'required' : _("Student field is required."),
            },
            'route' : {
                'required' : _("Route field is required."),
            },
            'date_of_issue' : {
                'required' : _("Date of Issue field is required."),
            },
            'valid_up_to' : {
                'required' : _("Valid up to field is required."),
            },
        }

templates/transports/bus_passes.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <section id="content">
        <div class="container">
             <div class="c-header">
                <h2>{{title}}</h2>
            </div>

            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{title}}</div>

                <div class="ah-search">
                    <form method="get" action="{% url 'transports:bus_passes' %}" class="ahs-input">
                        <input name="q" type="text" placeholder="Start typing..." class="ahs-input">

                        <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
                        <input type="submit" class="hidden" />
                    </form>
                </div>

                <ul class="ah-actions actions a-alt">
                    <li>
                        <a href="" class="ah-search-trigger" data-ma-action="ah-search-open">
                            <i class="zmdi zmdi-search"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Filter" class="filter_button" href="">
                            <i class="zmdi zmdi-filter-list"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Create Transport" href="{% url 'transports:create_bus_pass' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Delete selected items" data-id="" href="{% url 'transports:delete_selected_bus_passes' %}" data-text="{{confirm_delete_selected_message}}" data-title="Are you sure?" class="action-button reload selected-items-button">
                            <i class="zmdi zmdi-delete"></i>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="card">

                {% if instances %}

                <div class="table-responsive">
                    <table id="data-table-basic" class="table table-striped table-vmiddle">
                        <thead>
                            <tr>
                                <th style="width:20px;"></th>
                                <th data-column-id="id" data-type="numeric">ID</th>
                                <th>Student Name</th>
                                <th>Boarding Point</th>
                                <th>Date of Issue</th>
                                <th>Valid up to</th>
                                <th data-column-id="action">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% load el_pagination_tags %}
                            {% paginate 21 instances %}
                            {% for instance in instances %}
                            <tr class="check_items_row">
                                <td style="width:20px;">
                                    <div class="checkbox lgi-checkbox m-t-5">
                                        <label>
                                            <input class="check check_item" type="checkbox" value="{{instance.pk}}" name="delete_item">
                                            <i class="input-helper"></i>
                                        </label>
                                    </div>
                                </td>
                                <td><a href="{% url 'transports:bus_pass' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                                <td>{{instance.student}}</td>
                                <td>{{instance.boarding_point}}</td>
                                <td>{{instance.date_of_issue}}</td>
                                <td>{{instance.valid_up_to}}</td>
                                
                                <td>
                                    <a href="{% url 'transports:bus_pass' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                                    <a href="{% url 'transports:edit_bus_pass' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                                    <a data-id="{{instance.pk}}" href="{% url 'transports:delete_bus_pass' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!--pagination -->
                <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                    {% get_pages %}
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="pagination">
                                {% show_pages %}
                            </div>
                        </div>
                        <div class="col-sm-6 infoBar">
                            <div class="infos">
                                Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <!--pagination-->
                {% else %}
                    {% include 'includes/not_found.html' %}
                {% endif %}
            </div>

        </div>
    </section>
{% endblock %}

{% block filter_box %}
<div class="filter-box">
     <form method="get" action="{% url 'transports:bus_passes' %}">
        <div class="card">
            <div class="card-header">
                <h2>Filter <small></small></h2>
                <span class="back-button-poupup palette-Cyan bg white btn btn-default btn-icon-text waves-effect"><i class="zmdi zmdi-arrow-back"></i> Back</span>
            </div>

            <div class="card-body card-padding">
                <div class="form-group fg-line">
                    <label>Query</label>
                    <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
                </div>

                 <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
            </div>
         </div>
     </form>
</div>
{% endblock %}

{% block static %}
    {% load static %}
{% endblock %}

templates/transports/transports.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
    <section id="content">
        <div class="container">
             <div class="c-header">
                <h2>{{title}}</h2>
            </div>

            <div class="action-header palette-theme {{current_theme}} bg clearfix">
                <div class="ah-label hidden-xs palette-White text">{{title}}</div>

                <div class="ah-search">
                    <form method="get" action="{% url 'transports:transports' %}" class="ahs-input">
                        <input name="q" type="text" placeholder="Start typing..." class="ahs-input">

                        <i class="ah-search-close zmdi zmdi-long-arrow-left" data-ma-action="ah-search-close"></i>
                        <input type="submit" class="hidden" />
                    </form>
                </div>

                <ul class="ah-actions actions a-alt">
                    <li>
                        <a href="" class="ah-search-trigger" data-ma-action="ah-search-open">
                            <i class="zmdi zmdi-search"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Filter" class="filter_button" href="">
                            <i class="zmdi zmdi-filter-list"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Create Transport" href="{% url 'transports:create_transport' %}">
                            <i class="zmdi zmdi-plus"></i>
                        </a>
                    </li>
                    <li>
                        <a title="Delete" data-id="" href="{% url 'transports:delete_selected_transports' %}" data-text="{{confirm_delete_selected_message}}" data-title="Are you sure?" class="action-button reload selected-items-button">
                            <i class="zmdi zmdi-delete"></i>
                        </a>
                    </li>
                </ul>
            </div>

            <div class="card">

                {% if instances %}

                <div class="table-responsive">
                    <table id="data-table-basic" class="table table-striped table-vmiddle">
                        <thead>
                            <tr>
                                <th style="width:20px;"></th>
                                <th>ID</th>
                                <th>Choice</th>
                                <th>Traveller</th>
                                <th>Boardng Point</th>
                                <th>Morning Bus</th>
                                <th>Evening Bus</th>
                                <th data-column-id="action">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% load el_pagination_tags %}
                            {% paginate 21 instances %}
                            {% for instance in instances %}
                            <tr class="check_items_row">
                                <td style="width:20px;">
                                    <div class="checkbox lgi-checkbox m-t-5">
                                        <label>
                                            <input class="check check_item" type="checkbox" value="{{instance.pk}}" name="delete_item">
                                            <i class="input-helper"></i>
                                        </label>
                                    </div>
                                </td>
                                <td><a href="{% url 'transports:transport' pk=instance.pk %}">{{instance.auto_id}}</a></td>
                                <td>{{instance.choice|default:"-"}}</td>
                            {% if instance.student %}
                                <td>{{instance.student.name|default:"-"}}</td>
                            {% else %}
                                <td>{{instance.staff|default:"-"}}</td>
                            {% endif %}
                                <td>{{instance.boarding_point|default:"-"}}</td>
                                <td>{{instance.morning_bus|default:"-"}}</td>
                                <td>{{instance.evening_bus|default:"-"}}</td>
                                
                                <td>
                                    <a href="{% url 'transports:transport' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-eye"></i></a>
                                    <a href="{% url 'transports:edit_transport' pk=instance.pk %}" class="btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-edit"></i></a>
                                    <a data-id="{{instance.pk}}" href="{% url 'transports:delete_transport' pk=instance.pk %}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" class="action-button remove btn btn-default btn-icon waves-effect waves-circle waves-float"><i class="zmdi zmdi-delete"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!--pagination -->
                <div class="bootgrid-footer container-fluid" id="data-table-selection-footer">
                    {% get_pages %}
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="pagination">
                                {% show_pages %}
                            </div>
                        </div>
                        <div class="col-sm-6 infoBar">
                            <div class="infos">
                                Showing {{title}} <span class="current_page_index">{{ pages.current_start_index }}</span> - <span class="current_end_status">{{ pages.current_end_index }}</span> of <span class="total_count">{{ pages.total_count }}</span>
                            </div>
                        </div>
                    </div>
                </div>
                <!--pagination-->
                {% else %}
                    {% include 'includes/not_found.html' %}
                {% endif %}
            </div>

        </div>
    </section>
{% endblock %}

{% block filter_box %}
<div class="filter-box">
     <form method="get" action="{% url 'transports:transports' %}">
        <div class="card">
            <div class="card-header">
                <h2>Filter <small></small></h2>
                <span class="back-button-poupup palette-Cyan bg white btn btn-default btn-icon-text waves-effect"><i class="zmdi zmdi-arrow-back"></i> Back</span>
            </div>

            <div class="card-body card-padding">
                <div class="form-group fg-line">
                    <label>Query</label>
                    <input name="q" type="text" class="form-control" placeholder="Enter your query..." />
                </div>

                 <div class="m-t-20">
                    <button type="submit" class="btn btn-info waves-effect">Submit</button>
                </div>
            </div>
         </div>
     </form>
</div>
{% endblock %}

{% block static %}
    {% load static %}
{% endblock %}